qier222/YesPlayMusic

jsconfig.json

添加了 jsconfig.json 用于编辑器支持路径别名解析，方便代码阅读和调试。

feat: add config to resolve path alias.

---

src/components/Cover.vue

visibility属性不能应用过渡效果，导致hover的时候有点生硬。。

修该 visibility 为 opacity

---

package.json
src/electron/ipcMain.js
src/store/actions.js
vue.config.js
yarn.lock

1. Increase the timeout time to prevent blocking the rendering process
2. Use the modification package to solve the problem that song information may not be available and repeatedly requested.

fix(unblockMusic): the song information may fail to be fetched and reduce the request time

---

src/utils/common.js

close https://github.com/qier222/YesPlayMusic/issues/84

fix(common/isTrackPlayable): add cloud storage judgement logic

---

README.md

@qier222 
Now we can get YesPlayMusic from [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) by PR [#99129](https://github.com/Homebrew/homebrew-cask/pull/99129).

[+] Install by using Homebrew > README.md

---

src/locale/lang/en.js
src/locale/lang/zh-CN.js
src/views/playlist.vue

可用搜索关键字：歌名、歌手名、专辑名
这功能目前主要是我想用😂

Add search in playlist ｜ 增加歌单内的歌曲搜索

---

src/views/lyrics.vue

prevent lyric selection from seeking
prettier check is skipped.

fix: prevent lyric selection from seeking

---

src/locale/lang/en.js
src/locale/lang/zh-CN.js
src/store/initLocalStorage.js
src/store/mutations.js
src/utils/Player.js
src/views/playlist.vue
src/views/settings.vue

增加输出设备的选择(开发环境下需要build后才可看到其他设备)
无设置情况下系统默认设备，若设置过设备则以后启动默认选择当前设置的输出设备，若该设备找不到则选择系统默认输出设备

Added output devices selection | 增加输出设备选择

---

src/locale/index.js
src/locale/lang/en.js
src/locale/lang/zh-CN.js
src/views/settings.vue

可在electron以外的环境中切换输出设备（申请麦克风权限），electron默认有权限故一切OK。😊

fix: audio output device switching outside electron app | 修复输出设备切换

---

.gitattributes

fix the error binary files are considered changed after git clone

chore: set binary type for files

---

package.json
src/electron/ipcMain.js
src/locale/lang/en.js
src/locale/lang/zh-CN.js
src/store/initLocalStorage.js
src/utils/Player.js
src/views/settings.vue
yarn.lock

1. 修复了一些音频设备切换在Safari浏览器下会导致无法播放的bug
2. 完善了下MediaSession
3. 增加Discord Rich Presence支持(默认关闭) **~~(请原谅我又整了点骚的😂)~~**

feat: Add DiscordRichPresence | 增加DiscordRichPresence

---

src/background.js
src/components/Navbar.vue
src/electron/menu.js
src/locale/lang/en.js
src/locale/lang/zh-CN.js

1. Navbar 补上 i18n
2. GitHub 大小写统一

update: Navbar i18n & Github -> GitHub

---

src/utils/Player.js
src/views/playlist.vue

1. 有部分歌曲可能无歌手信息或者专辑信息（我在自己上传到云盘的歌曲中遇到这种情况，如图所示的歌曲），此时无信息的空值为`null`(不懂为啥不是个空字符串😂)，执行`toLowerCase()`会报错，此PR修复了这个bug
2. 给输出设备切换添加了运行环境检测

fix: search bug when searching in playlist

---

src/background.js
src/store/plugins/sendSettings.js

在electron初始化时判断外观设置，防止在暗色模式设置下启动闪白。
resolve #512

fix(electron): set appearance during init of electron window

---

src/locale/lang/zh-CN.js

fix: fix typo

---

src/utils/Player.js

fix(player): fix cannot switch next track in personalFM

---

src/utils/Player.js

fix(player): fix can't read prop seek of null

---

src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/store/initLocalStorage.js
src/utils/db.js
src/views/home.vue
src/views/settings.vue

feat(cache): add songs cache limit feature

---

src/App.vue
src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/store/initLocalStorage.js
src/views/settings.vue

feat(settings): add show music library default setting

---

src/views/settings.vue

fix(settings): fix typo

---

src/App.vue

fix(lyrics): fix resetting the previous page when lyrics switchoff

---

src/views/newAlbum.vue

fix: newAlbum issue (#573)

---

src/views/lyrics.vue

修正一下上次性能改善带来的样式错位。
另外说现在是两层filter叠加变成顶层一层filter，渲染出的样式还是有点差别。
觉得这个只能取舍了，多层的好看，单层的性能好一点。

fix(lyrics): fix style

---

src/App.vue
src/components/TrackList.vue
src/electron/services.js
src/store/mutations.js
src/utils/ui.js
src/views/lyrics.vue

在歌词界面隐藏滚动条，且禁止底层页滚动。
close #571

fix(lyrics): hide the scrollbar in lyrics page

---

src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/store/initLocalStorage.js
src/views/lyrics.vue
src/views/settings.vue

feat(lyrics): add static lyrics background

---

src/views/playlist.vue

https://user-images.githubusercontent.com/16725418/116460633-d875e600-a899-11eb-8b2d-d6213d5e377f.mov
相关Issue: #555 
点击搜索按钮后打开搜索框同时执行`loadMore(500)`加载更多歌曲
其余与普通歌单内搜索没啥区别

feat: search in likepage | `我喜欢的音乐`歌单内搜索

---

src/electron/globalShortcut.js

feat(shortcut): add show-hide keyboard shortcut

---

src/views/artist.vue

Add artist description

---

src/components/TrackListItem.vue

feat: add song title translate | 添加歌名翻译

---

src/components/DailyTracksCard.vue
src/components/ModalAddTrackToPlaylist.vue
src/components/ModalNewPlaylist.vue
src/components/TrackList.vue
src/locale/lang/en.js
src/locale/lang/zh-CN.js
src/views/album.vue
src/views/artist.vue
src/views/library.vue
src/views/mv.vue
src/views/playlist.vue

Add localizations

---

src/locale/lang/en.js
src/locale/lang/zh-CN.js
src/views/library.vue
src/views/searchType.vue

fix: Add i18n for playlist context menu

---

src/views/search.vue

feat: show toast when search failed

---

src/App.vue
src/background.js
src/electron/ipcMain.js
src/electron/windowsTaskbar.js
src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js
src/store/initLocalStorage.js
src/views/settings.vue

实现了任务栏进度条、控制按钮
按钮直接复用 touchbar 的素材图标
显示音乐封面这个，可能需要 Windows API , 有空尝试使用 ffi-napi 调用 Windows API 能不能实现
https://github.com/qier222/YesPlayMusic/issues/129

feat: windows taskbar media control.

---

src/views/album.vue

feat : Support separate album by disc | 支持专辑按碟分类

---

src/background.js
src/electron/ipcMain.js
src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js
src/store/initLocalStorage.js
src/views/settings.vue

close #862 
close #873
close #892 
close #725

feat: more operations for close | 为关闭app操作提供更多选项

---

src/background.js
src/electron/ipcMain.js
src/electron/ipcRenderer.js
src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js
src/views/settings.vue

trace #936 
<del>已知问题：https://github.com/qier222/YesPlayMusic/issues/936#issuecomment-929021500</del>  fixed
macos需单独处理

增强并明确关闭app的相关行为

---

src/views/library.vue

为 getRandomLyric() 添加判断, 避免保存方法死循环引发应用页面卡死.
close #1019

修复 issues #1019

---

src/components/TrackListItem.vue
src/views/album.vue

fix: disc color

---

src/views/settings.vue

feat(settings): update URL to our UNM fork's

---

src/utils/Player.js

fixed #1108
- Before creating Blob
- After creating Blob (by playing 5 cached songs twice)
- After running GC

fix(player): release object urls

---

src/views/lyrics.vue

fix: firefox lyrics scrollbar

---

src/electron/ipcMain.js
src/utils/Player.js
src/views/settings.vue

feat: allow customizing UNM's sources

---

src/views/library.vue

Closed #1133 (把 commit history 清乾淨一點)
Fixed #1019 #1127 #1067 #1064 #1058 #1022 
https://github.com/isNijikawa/YesPlayMusicBugFix/releases/tag/v0.4.2.1

refactor(views/library): 修改取词逻辑

---

src/views/library.vue

Seems work in lyrics whose lines are fewer than 3.
Fixed #1019

fix(views/library): better lyric-picking logic

---

netease_api/routes/index.js
src/api/user.js
src/components/TrackListItem.vue
src/store/actions.js
src/views/library.vue

feat: 增加我的听歌排行 (#274)

---

src/utils/lyrics.js

fix: lyrics sort

---

src/components/ContextMenu.vue

fix preview:
fix #1204 
fix #830

fix: context menu position

---

netease_api/routes/index.js
src/api/playlist.js
src/utils/Player.js
src/views/library.vue

feat: 增加心动模式/智能播放 (#323)

---

src/utils/lyrics.js
src/views/lyrics.vue

现在会一直过滤掉`作曲 : 无`与`作词 : 无`
对于纯音乐，如果作词作曲与作者信息一致，会过滤掉作词作曲

feat: better lyrics filter

---

src/components/FMCard.vue
src/components/Player.vue
src/electron/ipcRenderer.js
src/utils/Player.js
src/views/lyrics.vue

fix : PersonalFM can not found next track

---

src/utils/Player.js

Fixed autoplay on mobile by properly setting the "on end" callback for howler.

fix: sets "onend" callback for howler properly (#1090)

---

Dockerfile

fix: docker build failed #1258

---

src/utils/lyrics.js

Fully rewrited and improved the performance.

refactor(utils/lyrics): support multi-timestamp lyrics

---

vue.config.js

优化打包体积，移除生产环境不必要的 map 文件；webpack 添加 LimitChunkCountPlugin 用以解决 chunk 包太多的问题

feat: 优化打包体积

---

LICENSE

Copyright year update to 2022

---

src/components/Player.vue
src/views/lyrics.vue

fix: 修复部分按钮失效的问题

---

packages/renderer/src/utils/player.ts

从 https://github.com/qier222/YesPlayMusic/commit/fbf695eb160a9b6fa0252cb15cfdd73eaf2da99a 移植，测试没问题，不确定会不会影响到其他的调用

feat(utils/player): 播放、暂停时淡入淡出 

---

README.md

Update README.md: 添加了 Scoop 安装方式介绍

---

src/utils/request.js

Fixes #1441
Fixes #1431
Fixes #1098
Fixes #975

fix(utils/request): redirect when token has expired

---

src/renderer/api/personalFM.ts
src/renderer/components/ArtistsInline.tsx
src/renderer/components/FMCard.tsx
src/renderer/components/Player.tsx
src/renderer/hooks/usePersonalFM.ts
src/renderer/utils/player.ts

~待解决：APP启动时，FMCard拿不到数据任何数据，需要点击`下一首`来刷新数据~
已修复

feat: 实现私人FM

---

package.json
src/utils/platform.js

revert: isCreateTray 在瀏覽器環境應永遠為應永遠為 false 

---

restyled.yml

https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

ci: configure restyled.io better

---

src/utils/request.js

Overriding `realIP` param with an environment variable.

feat(utils/request): override realIP with env var

---

src/renderer/components/Lyric/Player.tsx
src/renderer/components/Sidebar.tsx
src/renderer/components/SvgIcon.tsx
src/renderer/utils/player.ts

Update playing status on sidebar playlists

---

src/views/lyrics.vue

Improve the animation smoothness with `transform: scale`

---

src/views/loginAccount.vue

feat: 使用svg输出登陆二维码

---

src/views/lyrics.vue

refactor(views/lyrics): tweak size

---

src/electron/ipcMain.js
src/utils/Player.js
src/utils/base64.js
src/views/settings.vue

fix: bilibili音源无法播放的问题

---

src/api/track.js
src/utils/Player.js
src/views/settings.vue

feat: 支持Hi-Res

---

src/api/track.js
src/utils/Player.js

fix: 错误的选择了音源质量

---

src/views/lyrics.vue

fix #1603
#1622 的另一种实现，基于transform

fix: 歌词页视觉效果缺陷

---

src/electron/tray.js

留个TODO：
当v2托盘实现在经过我所有的设备测试后反向移植到v1

fix: 部分linux发行版环境的托盘行为

---

src/views/library.vue

fix: 音乐库收藏的歌单少了第一张歌单

---

.github/workflows/build.yaml

As titled,
checks: https://github.com/kuohuanhuan-forkonly/YesPlayMusic/actions/runs/2418981737

chore(ci/cd): update some Workflows' version

---

src/api/playlist.js
src/utils/playList.js
src/views/explore.vue
src/views/home.vue
src/views/playlist.vue

修复了可能是由于接口更换，导致无法获取到私人推荐歌单的问题
close #1664 
> (PS:  其实这个修改已经在我的硬盘上躺了快一个月了，但是一直没有人反馈类似的问题，导致我一直以为只有我出现了这个问题）

fix: 私人推荐歌单

---

src/views/mv.vue

Add context menu on MV page

---

src/views/lyrics.vue

feat: Add "Volume Control" to Lyrics Page

---

src/components/Player.vue
src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js

Add unlike text to like button when hover event triggers

feat: Add status text to like button when hover event triggers

---

Dockerfile
docker-compose.yml
docker/nginx.conf.example

1. use `awk` to find NCMAPI version instead of `jq`
2. separate nginx config from `Dockerfile`
3. mount local time and time zone in `docker-compose.yml`

Dockerfile refactor

---

package.json

修个依赖，跟进上游的ncm api，解决邮箱登录问题，在Windows上测试通过。

fix: 更新api以尝试解决邮箱登录问题

---

package.json

已在 Windows 10 Pro 上测试通过。
内容:
UNM Rust 0.3.0--->0.4.0
NCM api ---> latest

deps : 更新依赖以解决手机号登录问题；UnblockNeteaseMusic 更新

---

src/utils/Player.js

fix: player volume bug

---

src/components/TrackList.vue
src/components/TrackListItem.vue
src/views/album.vue

fix(tracklist): TrackListItem 序号问题

---

src/utils/request.js
src/views/loginAccount.vue

Fix the issue when NCMapi is not under the same domain as the one frontend uses.
The original method using vercel to proxy requests may cause latency under some circumstances.

fix(request): cross domain api issue

---

src/views/artist.vue

fix(artist): 艺人页面专辑区不显示精选集

---

src/locale/lang/en.js
src/locale/lang/tr.js
src/locale/lang/zh-CN.js
src/locale/lang/zh-TW.js
src/views/settings.vue

fix: add some translation

---

packages/web/i18n/locales/en-us.json
packages/web/i18n/locales/zh-cn.json
packages/web/pages/Settings/Player.tsx

Add volume slider in Settings > Player to improve user experience with output devices in case their sensitivity is too high.

feat(web): volume control

---

src/views/loginAccount.vue

https://github.com/qier222/YesPlayMusic/issues/2093

fix(#2093): clear qrcode watch

---

packages/desktop/main/appServer/routes/r3play/audio.ts
packages/desktop/package.json
packages/shared/CacheAPIs.ts
packages/shared/api/Track.ts
pnpm-lock.yaml

feat: UNM supported

---

src/components/CoverRow.vue
src/components/TrackListItem.vue
src/views/album.vue

fix: 纠正脏标的判断

---

package.json
src/store/initLocalStorage.js
src/utils/request.js
src/views/settings.vue
yarn.lock

[NeteaseCloudMusicApi 更新：请求参数换成官方 PC 客户端参数, 尝试绕过风控](https://gitlab.com/Binaryify/neteasecloudmusicapi/-/merge_requests/25/diffs?commit_id=016fe7c285601fd022eecd5a52ed957cc4da7765)
不确定是否可以解决。顺便添加realIP设置项作为可选方案。
查看↓
Fixed #2299
Fixed #2304 
Fixed #2308 
Fixed #2309 
Fixed #2310 
Fixed #2311 
Fixed #2312 
Fixed #2313

网易云登录 帐号冻结问题

---

src/components/Player.vue

use "media key" on keyboard to manage player, toogle pause, prev song and next song
通过键盘上的媒体按键控制播放器. 切换暂停，切上一首下一首歌曲

feat: support media button
