qier222/YesPlayMusic

src/views/loginAccount.vue
把`.replaceAll()`换成了`.replace(/\s/g, '')`
Chromium 84及以下不支持`replaceAll()`
https://caniuse.com/?search=replaceall
=> 兼容Chromium 84及以下

README.md, src/config/request.js, src/utils/request.js
First, I separate the `baseURL` option from `utils/request.js`.
And, I replaced the ugly if-statement with Map, and I also make the message user-friendly since this project is written for users, not only for developers.
And also, I removed the useless "alert", it is useless and annoying for users.
=> Make configuring baseURL easier and make the errors friendly 

src/components/Player.vue, src/store/actions.js, src/store/index.js, src/store/initLocalStorage.js, src/store/mutations.js
目前的音乐加载初始化逻辑有两个问题:
1. 没必要加载默认设置的音乐
2. 打开app之后初始音乐会加载两次 只要页面发生点击就会触发第二次 所以关闭了autoUnlock
=> refactor: Adjusting music initialization logic

src/views/album.vue
description can contain `\n` add `white-space: pre-line` to make it display better.
-----
=> fix: description style with newline

public/index.html, src/App.vue, src/components/CoverRow.vue, src/components/MvRow.vue, src/components/Navbar.vue, src/components/Player.vue, src/components/TrackList.vue, src/components/TrackListItem.vue, src/electron/tray.js, src/views/album.vue, src/views/artist.vue, src/views/artistMV.vue, src/views/explore.vue, src/views/home.vue, src/views/library.vue, src/views/loginUsername.vue, src/views/lyrics.vue, src/views/mv.vue, src/views/playlist.vue, src/views/search.vue, src/views/searchType.vue, src/views/settings.vue
Make the scrolling animation smoother using cubic bezier (0, 0, 0, 1) (realized with JavaScript) and add blur effect to lyrics.
Add sliding animation to panels when opening and closing them.
Add disappearing animation to tracklist items.
Also, I'm planning to change (0, 0, 0, 1) to (0.2, 0, 0, 1), still working in progress.
---
使用贝塞尔曲线 (0, 0, 0, 1)（用 JavaScript 实现），使歌词滚动更加流畅，并且为之添加模糊效果。
为面板添加滑动打开关闭动画。
为列表项添加背景动画
同时，我打算把 (0, 0, 0, 1) 改成 (0.2, 0, 0, 1), 但是这就不能用二次函数了，所以还正在开发中。
=> Update animations for lyrics, panels and tracklists | 为歌词、面板和列表更新动画

src/views/lyrics.vue
修复了在生产环境中歌词页出现的 `ev.target.children.forEach is not a function`。此问题在 #280 中提出。
=> Fix ev.target.children.forEach is not a function (#280)

package.json, src/electron/ipcMain.js, yarn.lock
在Large Image显示歌曲名是看到隔壁Spotify的，感觉该给整一个
主要的还是更改了淘宝源到yarn源
=> fix: change source and add track name in discord large image text

src/views/playlist.vue
1. 增加歌单内搜索
2. 搜索框位置基于`playlist-info`相对定位
3. 在搜索框输入会有0.6秒的防抖
4. 根据此Issue的说法 我修改了`loadMore()` 从每次50首到500首
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/452#issuecomment-474221568
目前的问题是，如果用户歌单过大，那么歌单内搜索会无法搜索到还未请求detail的歌，除非用户拉到了歌单底部手动`loadMore()`
诚然可以在用户搜索时获取所有歌的detail，但我暂不清楚网易云官方是怎么做的，所以没有点子。
需要一些主意
目前效果：
https://user-images.githubusercontent.com/16725418/111831577-8cdf2c80-892a-11eb-857d-eb54a173b103.mp4
=> feat: add search in playlist | 增加歌单内搜索

src/utils/nativeAlert.js, src/views/loginAccount.vue, src/views/playlist.vue
Windows 上的 Electron 存在一个 bug，页面内使用 alert 弹出提示框，点击确认之后页面内的 input 控件无法 focus，需要通过切换窗口焦点解决。[electron/electron #19977](https://github.com/electron/electron/issues/19977)
主要问题场景为 Windows 平台上，登录时输入不正确/密码不正确时确认提示后无法编辑用户名和密码。
该 Pull Request 通过判断当前环境，在 Electron 环境上使用 [showMessageBoxSync](https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxsyncbrowserwindow-options) API 替换 alert 函数，以解决该问题。
=> Fix alert issue on Windows by using native messageBox

src/utils/auth.js
相关Issue： #538 
登出时更新一下`LocalStorage-data`中的`likedSongPlaylistID`
=> fix: likelist does not change when account switching | 修复切换账号后喜欢列表不变

src/views/lyrics.vue
调整了下css，优化了歌词动态背景的GPU占用。
一台7700HQ的HD630，测试功耗会降低4w左右，频率降低0.4Ghz，占用率降低10-25%之间。
一台MBP13的Iris Plus 645，频率降低0.2-0.3Ghz，占用率降低20-30%左右。
应该可以还好，暂时先提交。
#484
=> perf(lyrics): optimize GPU usage for dynamic lyric backgrounds

src/views/settings.vue
修复切换框Disabled
因为Electron外不显示，那就不需要考虑权限问题😂
=> fix: output device switch | 修复设备切换

src/utils/db.js
歌手名的问题，自己上传的歌曲很多是没有歌手名字的，用`Unknown`替代。
报错原因是索引了`TrackInfo.artists`的0号元素，但`TrackInfo`里没有`artists`。
相关Issue: #720 #759 #773 #763 (其实是我自己听着听着发现听不了 修完搜了搜发现还挺多Issue的😂)
=> fix: cloudpan music playing error | 云盘音乐播放错误

src/views/artist.vue
=> fix: empty Album artist page can't open | 修复当歌手没有专辑时无法打开歌手页的BUG

README.md, package.json, src/electron/ipcMain.js, src/utils/Player.js, src/utils/nativeAlert.js, vue.config.js, yarn.lock
- 把目前已經不積極維護的 UnblockNeteaseMusic 替換成我們積極維護的分支。
- 解決 UnblockNeteaseMusic 卡住介面的 bug。
- 預設開啟 bilibili 和 `ytdlp`
- 音樂是亂序 match
- 使用 `Promise.any` 而非 `Promise.all` 取得各音源音樂，
速度比較快，但不能照著指定的順序 match（原則上 YPM 應該不受這影響）
應該會另外開分支進行。
=> Use actively maintained unm

src/background.js
运行环境：Windows 11 21H2
出现的问题：启动之后无法自动打开全局快捷键，需要到设置中手动关闭再打开。
测试：
```shell
yarn electron:serve
```
报错：
```
TypeError: Cannot read property 'setMenu' of undefined
at App.eval (webpack:///./src/background.js?:357:59)
at App.emit (events.js:315:20)
```
在 Windows 电脑上可能无设置dock的方法，故加上是否为空的判断。
结果：在本机的Electron上能够在启动时打开全局快捷键。
=> to fix: #1063 #1010

src/components/Toast.vue
After:
Before:
添加重复歌曲到歌单时发现`Toast`被挡在后面了，狂摁了3秒添加寻思咋回事呢😂
=> fix: `toast` covered by `modal` | 修复`toast`被`modal`遮挡

src/views/library.vue
修复因为一句歌词同时存在多个时间戳，导致library取词取到时间戳的bug
lyric:
before:
after:
=> fix: library extract lyric part

.dockerignore, Dockerfile, README.md, docker-compose.yml
=> chore: 支持 Docker 部署 (#1195)

Dockerfile
修復 #1212 ，順便固定 base image 版本，避免未來 base image 出問題導致打包失敗
=> fix: docker build image error (#1212)

src/utils/lyrics.js
修复在之前的更改中，错误的对全为空格的内容进行trim()操作，导致歌词页面的歌词进度错位的问题
=> fix: wrong trim all white space lyric

src/utils/Player.js
私人FM的后续反馈修复
当没有获取到数据时(非超时)，添加了一个最多5次的重试，当全部重试失败时，才反馈和引导用户手动切歌
=> fix: retry when personalFM not found data

src/App.vue
=> fix: firefox scrollbar

src/components/DailyTracksCard.vue
=> fix(components/DailyTracksCard): 修复了每日推荐在 Safari 不显示圆角的bug

packages/renderer/src/pages/Login.tsx, packages/renderer/src/utils/cookie.ts
1. 修复因为replace函数导致的bug
- 原来的replace('HTTPOnly','')函数只能替换一个，所以替换为replaceAll。
- 在扫码返回的cookie中HTTPOnly是以'; HTTPOnly;'出现的，为了能够同时替换含有空格和不含空格的格式，使用了正则表达式。
2. 支持二维码登录
=> feat: 支持二维码登录

.github/workflows/build.yaml
目前 YPM 的 snapcraft_token 似乎失效了？但 0.4.4 release 前還是得解決 snapcraft 的問題。
=> fix(ci/build): 暫時不要登入

src/renderer/utils/lyric.ts
- 可以拉出角色 (role) 和名字 (name)：
`const { role, name } = line.groups as { role: string, name?: string }`
- 移除掉某些不需要的 regex 部分（如 `\s\S`）
- 簡化部分 regex（如 `(:|：)` 更改為 `[:：]`）
- 增加測試 (<https://regexr.com/6j8pf>)
=> refactor(utils/lyric): more powerful role matcher

src/views/loginAccount.vue
渲染 384px 的 QR Code，而顯示在 192px 的方框中。這樣 QR Code 大小不變，但清晰度為原本的兩倍。
Fixed #1562
=> fix(views/loginAccount): improve clarity of QR Code

src/utils/Player.js
修复长时间暂停后重新播放会停住的问题
- 音频资源会过期导致无法访问
- 因为我们直接将获取到的ncm audio url给howler播放，但是howler不会一边播放一遍把整首歌曲都缓存
所以在长时间暂停后，howler就无法获取音频后面没有缓存的部分，导致音频无法播放
监听hower的`loaderror`事件，这只是html5 audio MediaError的一个封装
当`loaderror`时，重新获取一个新的audio url并创建新的howler实例
大部分情况下，面临的问题是播放了一小段之后会停住，由于在v1中我们总是应用`fade-in-out`，当获取新的url后，会因为`fade-in`明显感觉到howler实例的改变
=> fix: 修复在长时间暂停后无法播放的问题

src/components/FMCard.vue, src/components/TrackList.vue, src/components/TrackListItem.vue
使歌名翻译一直处于歌名之后，其他信息之前
之前的行为：在专辑内，翻译和歌名中间可能会有其他信息
歌名翻译现在是半透明的，用于区分正在播放的歌名和翻译
FMCard的背景颜色现在会一直随着私人FM的歌曲改变
之前的行为：只有在FMCard里切歌才会改变
=> fix: 歌名翻译文本位置 & FMCard背景颜色

Dockerfile
现在 `master` 分支下的 [`Dockerfile`](../blob/master/Dockerfile) 未规定 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi/releases) 的版本，构建 Docker 后运行会报错：
<details>
```
YesPlayMusic    | internal/modules/cjs/loader.js:905
YesPlayMusic    |   throw err;
YesPlayMusic    |   ^
YesPlayMusic    |
YesPlayMusic    | Error: Cannot find module './generateConfig'
YesPlayMusic    | Require stack:
YesPlayMusic    | - /usr/local/lib/node_modules/NeteaseCloudMusicApi/app.js
YesPlayMusic    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
YesPlayMusic    |     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
YesPlayMusic    |     at Module.require (internal/modules/cjs/loader.js:974:19)
YesPlayMusic    |     at require …
```
=> fix(dockerfile): 设置 NCMAPI 版本

src/locale/lang/en.js, src/locale/lang/zh-CN.js, src/locale/lang/zh-TW.js, src/views/lyrics.vue, src/views/settings.vue
在全屏歌词页面添加了时间的显示，并且在设置页面中增加了是否显示的设置项。
歌词页面示例图片（见红框部分）：
设置页面示例图片（见红框部分）：
=> feat: Add time to lyric page

src/views/album.vue
album.company返回的不是null，是个空字符。
所以判断album.company!==null为真，显示了一个空的company
=> fix: album.company显示问题

package.json
The `@achrinza/node-ipc` version we use in 1.x does not allow
a version of Node.js greater than 17. As YesPlayMusic has been in
maintenance mode, we define our supported Node.js engine version
rather than upgrade this dependency.
It may indicate the Vercel platform to not use 18 (or greater) in their
deployment.
The error message is:
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.12.1"
=> chore: define node engines

src/components/Player.vue, src/utils/common.js
如图，选择时长大于一小时的曲目
在如下两个地方显示异常：
lyrics-page: 
player:
修复后：
lyrics-page:
player:
=> fix(player): 修复歌曲时长过长时的进度显示问题

src/utils/Player.js
修复某些情况下云盘中的音频格式不支持播放的问题，这种问题很少见，是因为某些 flac 文件在 chromium 中播放时会导致 ffmpeg 解码器出错，进而无法播放。
至于为什么 chromium 无法播放就不知道了，可能跟 flac 的文件格式不标准有关系，也可能是 chromium 的内部问题。本地的媒体播放器例如 VLC 都是可以正常播放的。
=> fix(player): Skip track when audio source not supported

src/components/Navbar.vue
在小尺寸下，这个导航栏有可能会和控制栏重叠（未hover时略显拥挤，hover时会重叠），增加了一个`max`函数来确定`padding`的最小值
Before：
After：
=> fix(NavBar): Fixed the issue of overlapping with the control bar

src/utils/Player.js
切换到下一首插队歌曲后，排在它后面的下一首歌会跟着从队列中消失。这个bug与 issue #1908, #1644 应该属于同一个问题，这个问题用文字描述比较抽象，这里上一张动图：
**原因：预加载歌曲会意外导致队列的下一首歌被移除。** 
获取下一首id时，队列中第一个元素会被移除并返回，这在切换下一首时没有影响，但在仅仅是为了“获得”的情况下，将导致其被意外移除
**思路：**
修改了方法 `_getNextTrack()`：永远只会返回队列第一个元素，不做移除操作，原本切换下一首需要的移除操作交给  `playNextTrack()` 完成。
=> fix(player): 插队曲目切换后下一首曲目丢失

Dockerfile, docker-compose.yml, docker/nginx.conf.example
- 扩展了一下 docker-compose.yml， 使得现在 docker 部署的实例，能够默认支持[网易云音乐解锁](https://github.com/UnblockNeteaseMusic/server)。
- 调整了一下 Dockerfile 里面的内容，使得能够在国内网络能够正常地 build YesPlayMusic 的镜像。
=> [Feature] support UnblockNeteaseMusic with docker-compose deploy.

src/components/Cover.vue
As you can see, the icon for the play button does not appear in Safari.
before:
after:
=> fix: play icon not appear in Safari

src/utils/Player.js
在阅读并理解了实现各种播放行为的代码逻辑后，我发现在实现"通过右键方式播放"的代码中缺少了设置显示状态的代码，导致当播放器处于隐藏状态时，无法更改其为显示状态。
```
if (!this._enabled) this._enabled = true;
```
我初步想法是补充这一逻辑代码即可，就像其他播放行为的实现逻辑一样，但我认为这个逻辑应该集中在 `play()` 函数中，当播放器开始播放歌曲时，确保其为显示状态。
Close #1965
=> Fix: 右键播放歌曲无法激活播放栏

.github/workflows/sync.yml
allow fork to sync with upstream automatically.
=> Upstream Sync

.github/workflows/build.yaml, src/utils/request.js
Close #2190
Close #2191
Close #2192
=> fix github action missing env

public/robots.txt
=> fix: 阻止搜索引擎爬虫爬取网站的内容

src/electron/ipcMain.js
I think this looks better than the app logo.
Closes #2069.
=> Use cover image for discord rpc

src/components/TrackListItem.vue, src/views/album.vue
使用 .prettierrc 配置重新格式化 *.vue，修复了 vercel 构建过程中 prettier 报错而无法完成构建的问题。
原问题日志可见 #2291.
Resolved #2291.
=> fix: fix build error due to ill-formatted *.vue

.github/workflows/build.yaml
actions/upload-artifact@v3 was deprecated at end of 2024.
=> Upgrade actions/upload-artifact to v4
